# Generated by Django 5.0.6 on 2024-06-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('data_entrada', models.DateField()),
                ('material', models.CharField(max_length=100)),
                ('exam_type', models.CharField(max_length=100)),
                ('results', models.TextField()),
                ('method', models.CharField(max_length=100)),
                ('reference_value', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
